spring.application.name=szp

# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASSWORD}
# spring.datasource.url=${DB_URL}
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.url=jdbc:postgresql://localhost:5432/szp-db
spring.datasource.driver-class-name=org.postgresql.Driver

security.jwt.secret-key=WPUqYj9PdV2za4a1fRBQ8iPfcH5hwGxru0OH7h5VNIf
security.jwt.expiration-time=3600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Опционально: имена таблиц в нижнем регистре (избегает проблем с регистром)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.defer-datasource-initialization=true